### ISSUE TITLE
How to convert CK+ dataset to .npy

### ISSUE THREAD

**Issue by fitrialif** [arundasan91/DeXpression#1]
# Load data
X = np.load('CKP_X.npy')
Y = np.load('CKP_Y.npy')

**Comment by arundasan91** [comment]
Please take a look at these awesome scripts:
1. https://github.com/rolanvc/cs295-PA1/blob/master/preproc.py
2. https://github.com/rolanvc/cs295-PA1/blob/master/preproc2.py
3. https://github.com/rolanvc/cs295-PA1/blob/master/preproc3.py
4. https://github.com/rolanvc/dexpression/blob/master/utils.py

**Comment by arundasan91** [comment]
@fitrialif , Hope these helped. Please reopen if you have any queries.

**Comment by fitrialif** [comment]
hi @arundasan91 ,
Thank you for the code.
I have ran this code until preproc3.py and the resize image was produce but when I try run utils.py code nothing happen. Still cannot convert to numpy format.

**Comment by arundasan91** [comment]
Hey @fitrialif , Maybe you're missing something. What you'd want to do is to understand what the function `filestoTFdata ` https://github.com/rolanvc/dexpression/blob/master/utils.py#L4-L33 is doing. You've to call that function with a list of filenames (absolute paths). The function is well documented. Let me know how it goes.

Thanks,
Arun

**Comment by fitrialif** [comment]
Hi... it's this how to run this code python utils.py /home/fitrialif/resize

I try run like this but there is no numpy output

**Comment by arundasan91** [comment]
@fitrialif , 

What you are doing is to run the `utils.py` file with an argument `/home/fitrialif/resize`. This won't work as:
1. The function is not expecting any arguments.
2. The function needs a list of filenames (absolute path).

Also, [Line 33](https://github.com/rolanvc/dexpression/blob/master/utils.py#L33) should ring some bells. The function is returning the concatenated array. 

If you'd want to save the arrays, add a line after [Line 38](https://github.com/rolanvc/dexpression/blob/master/utils.py#L38) to save the variables `images` and `labels` to disk. You can use `numpy.save` to do that.

What you need to do is to create a list of filenames say:
```
filelist = ['/home/fitrialif/resize/001.jpg', '/home/fitrialif/resize/002.jpg', '/home/fitrialif/resize/003.jpg']
```
You can use `os.listdir` or something similar for that. Maybe replace the `filelist` in [Line 37](https://github.com/rolanvc/dexpression/blob/master/utils.py#L37) with the one you create. 

Finally, run the code using `python utils.py`

**Comment by fitrialif** [comment]
`import tensorflow as tf
import os
import numpy as np
import cv2
def filestoTFdata(files):
    '''
    
    :param files:is a list of filenames of format E$_xxxxxxx.png representing images of emotions.
    The $ is a number from 1..7 representing the emotion (anger, contempt, disgust, fear, happy, sadness, surprise)
    
    :return: a list of (image) data, and a list of one-hot-arrays representing emotion labels 
    '''
    images= []
    labels = []
    for f in files:
        # get the filename. extract the E$ to acquire emotion label
        fn = os.path.basename(f)
        emo = int(fn.split('_')[0][1]) - 1
        #create a one-hot vector
        onehot = np.array([int(i==emo) for i in range(7)], dtype=np.uint8)
        #reshape to be as expected i.e. (1,7)
        emo_label = np.reshape(onehot, (1, 7))
        # add to list
        labels.append(emo_label)
        # read the imagee as grayscale
        img = cv2.imread(f, cv2.IMREAD_GRAYSCALE)
        # expand to that expected
        expanded_img = np.expand_dims(np.expand_dims(img,0),3)
        # convert to numpy array
        image = np.array(expanded_img)
        # add to list
        images.append(image)
        np.save('x.npy',images)
        np.save('Y_.npy',labels)
    # return lists of images and labels
    return images, labels

# test the function above
if __name__== "__main__":
    filelist = ['/home/fitrialif/PHDFitri/codeFER/preprocess_ck+/resize/']
    images, labels = filestoTFdata(filelist)`

and i run it `python utils.py` but i get this error

`Traceback (most recent call last):
  File "utils.py", line 41, in <module>
    images, labels = filestoTFdata(filelist)
  File "utils.py", line 18, in filestoTFdata
    emo = int(fn.split('_')[0][1]) - 1
IndexError: string index out of range
`

**Comment by fitrialif** [comment]
this is my code

import tensorflow as tf
import os
import numpy as np
import cv2
def filestoTFdata(files):
    '''

    :param files:is a list of filenames of format E$_xxxxxxx.png
representing images of emotions.
    The $ is a number from 1..7 representing the emotion (anger, contempt,
disgust, fear, happy, sadness, surprise)

    :return: a list of (image) data, and a list of one-hot-arrays
representing emotion labels
    '''
    images= []
    labels = []
    for f in files:
        # get the filename. extract the E$ to acquire emotion label
        fn = os.path.basename(f)
        emo = int(fn.split('_')[0][1]) - 1
        #create a one-hot vector
        onehot = np.array([int(i==emo) for i in range(7)], dtype=np.uint8)
        #reshape to be as expected i.e. (1,7)
        emo_label = np.reshape(onehot, (1, 7))
        # add to list
        labels.append(emo_label)
        # read the imagee as grayscale
        img = cv2.imread(f, cv2.IMREAD_GRAYSCALE)
        # expand to that expected
        expanded_img = np.expand_dims(np.expand_dims(img,0),3)
        # convert to numpy array
        image = np.array(expanded_img)
        # add to list
        images.append(image)
        np.save('x.npy',images)
        np.save('Y_.npy',labels)
    # return lists of images and labels
    return images, labels

# test the function above
if __name__== "__main__":
    filelist = ['/home/fitrialif/PHDFitri/codeFER/preprocess_ck+/resize/']
    images, labels = filestoTFdata(filelist)

i run using python utils.py but i get this error

Traceback (most recent call last):
  File "utils.py", line 41, in <module>
    images, labels = filestoTFdata(filelist)
  File "utils.py", line 18, in filestoTFdata
    emo = int(fn.split('_')[0][1]) - 1
IndexError: string index out of range

**Comment by arundasan91** [comment]
@fitrialif , I strongly suggest you brush up your Python skills and understand the context in which the code is running. Please refer my previous comment for `filelist`; it should be a list. If you've a friend who can lend a hand who knows Python, please meet with him/her and discuss this together.

Thanks,
Arun

**Comment by NomiMalik0207** [comment]
@fitrialif have you completed this task. I am facing the same problem can you help me??

**Comment by christiaan20** [comment]
The links to the files are dead. Can I assume that all 5876 are loaded and resized to 224x224x1 for inputting into the network?

**Comment by GaroBozadjian** [comment]
The links that you uploaded is not working, can you update them so we can use the CKP dataset please

**Comment by edgalsanchez** [comment]
The links are dead, can you update them? Please

**Comment by arundasan91** [comment]
@edgalsanchez , sorry. I checked for the repo, seems it was removed.

**Comment by arundasan91** [comment]
There are many projects which uses CK+ dataset. Unfortunately, since I have used my code in a private project, I cannot share it now. Please search for CK+ dataset in github.
