### ISSUE TITLE
Unable to recreate accuracy

### ISSUE THREAD

**Issue by christiaan20** [arundasan91/DeXpression#4]
Using 10-fold cross-validation on this architecture our best accuracy on the CKP database was around 40% that is on the validation set, ofcourse. I didn't use the code to generate the images because those links are dead. I just resized each image to a 224x244x1 unsigned 8-bit integer.

Is there something we have missed?

**Comment by arundasan91** [comment]
If you go through the paper again (https://arxiv.org/pdf/1509.05371.pdf), authors are not using 'neutral' emotion in their labels. Please take that into account and run the experiments again. Number of classes are 7 and not 8. That might be something that you've missed.
