### ISSUE TITLE
How to retrievie the picture from each layer?

### ISSUE THREAD

**Issue by BePhamVietnamese** [arundasan91/DeXpression#5]
I would like to extract pictures after each layer, same as shown in your papers.
Please help me on this.

![image](https://user-images.githubusercontent.com/38372714/45891390-a6ea3380-bdef-11e8-8f80-d9e0f88b5b98.png)

**Comment by arundasan91** [comment]
@BePhamVietnamese , just to clarify this is not a paper I published. You can contact the authors and see if they have some code to do that. In Keras, you could extract the activation of each layer (if you name the layer). A quick google search will give you many code snippets that might work.
